---
title: "code_blue"
author: "hamza"
date: "5/20/2021"
output: word_document
editor_options:
  chunk_output_type: console
---

```{r include=FALSE }
knitr::opts_chunk$set(
    comment = "",
    echo = F,
    fig.width = 12, 
    fig.height = 10,
    message = FALSE,
    warning = FALSE,
    tidy.opts = list(
        keep.blank.line = TRUE,
        width.cutoff = 150
        ),
    options(width = 150),
    eval = TRUE
)

```


```{r}
library(tidyverse)
library(readxl)
library(labelled)
library(gtsummary)
data <- read_csv("data_clean.csv")
data <- data[, 2:ncol(data)]

```

# Table 1 patients' characteristics grouped by resuscitation outcome

```{r}

var_label(data) <- list(
  Oncology_diagnosis_ = "Diagnosis",
  location_grouped = "Location",
  prec_cause_grouped = "Cause",
 arr_cond_grouped = "Condition"
)

tbl1_sum <- data %>% 
  dplyr::select(Oncology_diagnosis_, location_grouped, prec_cause_grouped, arr_cond_grouped, sucssessful_resuscitation)


tbl_summary(tbl1_sum, by = sucssessful_resuscitation, missing = "no") %>% add_p() %>% add_overall()  %>% add_n %>% bold_labels() %>% italicize_levels() %>% bold_p() %>% gtsummary::as_flex_table() 

```

# Risk factors affecting successful rescucitation 
using binary logistic regression 


```{r}

data$succ_resuc <- fct_recode(data$sucssessful_resuscitation, "1" = "y", "0" = "n")

m1 <- glm(succ_resuc ~ Oncology_diagnosis_ + location_grouped + prec_cause_grouped + arr_cond_grouped, family = binomial, data = data)

tbl_regression(m1, exponentiate = TRUE)

```

